### ISSUE TITLE
Release v0.7.5 is incompatible with Ubuntu 20.04

### ISSUE THREAD

**Issue by benjamin-thomas** [markusmoenig/Eldiron#14]
Hello!

I wanted to try your project out of curiosity (I bumped into your project looking at Rust game engines).

You may be already be aware of this incompatibility:

```
$ /usr/bin/creator_main 
/usr/bin/creator_main: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/bin/creator_main)
/usr/bin/creator_main: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/creator_main)
/usr/bin/creator_main: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/creator_main)
/usr/bin/creator_main: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/creator_main)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

For info, I did not quite understand what `Eldiron` is by reading the README. Is it a no-code tool? Will I program my game in Rust? Etc. You may be interested in that feedback to refine the README just a tad :)

**Comment by markusmoenig** [comment]
Hi Benjamin,

thanks for the report. Will look into it, in the meantime you can build Eldiron from the source as described in the Readme.

Yes, the Readme needs a bit of an overhaul, will do that soon, thanks.

**Comment by markusmoenig** [comment]
btw; l is it possible that your glic version is out of date ? Did you update the system ?

**Comment by benjamin-thomas** [comment]
Sound good to me :)

I'm closing this, now that you're aware of this potential problem for future versions.

Have a great day
