### ISSUE TITLE
Will there be detailed help documentation and tutorials?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [markusmoenig/Eldiron#26]
Not at all sure how to get started with it

**Comment by markusmoenig** [comment]
Hi, yes, there will be. There is some documentation I am working on at Eldiron.com and I posted a quick introduction video on my YouTube channel: https://www.youtube.com/channel/UCCmrO356zLQv_m8dPEqBUfA.

Also the Discord server is a good place to ask questions.

Once things get closer to v1 I will do more video tutorials and write more documentation. Right now its still not feature complete for v1 and I concentrate more on writing code.
